/**
 * Sheet name → Supabase table and header → DB column mapping for migration.
 * Derived from the workbook headers CSV. Skip placeholder columns (e.g. |||).
 */

export const SHEET_TO_TABLE: Record<string, string> = {
  'Orders': 'orders',
  'Order Items': 'order_items',
  'Order Add Ons': 'order_addons',
  'Payments': 'payments',
  'Fleet': 'fleet',
  'Expenses': 'expenses',
  'Card Settlements': 'card_settlements',
  'Vehicle Swaps': 'vehicle_swaps',
  'Customers': 'customers',
  'Journal Entries': 'journal_entries',
  'Cash Reconciliation': 'cash_reconciliation',
  'Maintenance': 'maintenance',
  'Lost Opportunity': 'lost_opportunity',
  'Employees': 'employees',
  'Timesheets': 'timesheets',
  'Cash Advance Schedules': 'cash_advance_schedules',
  'Transfers': 'transfers',
  'To Do': 'todo_tasks',
  'Merchandise': 'merchandise',
  'Misc Sales': 'misc_sales',
  'Reviews': 'reviews',
  'Recurring Bills': 'recurring_bills',
  'Directory': 'directory',
  'Paw Card': 'paw_card_entries',
  'UI Errors': 'ui_errors',
};

/** Load order (FK-safe). Skip: Orders (RAW), Config, User Permissions. */
export const MIGRATION_ORDER: { sheetName: string; tableName: string }[] = [
  { sheetName: 'Customers', tableName: 'customers' },
  { sheetName: 'Fleet', tableName: 'fleet' },
  { sheetName: 'Employees', tableName: 'employees' },
  { sheetName: 'Orders', tableName: 'orders' },
  { sheetName: 'Order Items', tableName: 'order_items' },
  { sheetName: 'Order Add Ons', tableName: 'order_addons' },
  { sheetName: 'Payments', tableName: 'payments' },
  { sheetName: 'Vehicle Swaps', tableName: 'vehicle_swaps' },
  { sheetName: 'Timesheets', tableName: 'timesheets' },
  { sheetName: 'Maintenance', tableName: 'maintenance' },
  { sheetName: 'Expenses', tableName: 'expenses' },
  { sheetName: 'Transfers', tableName: 'transfers' },
  { sheetName: 'Journal Entries', tableName: 'journal_entries' },
  { sheetName: 'To Do', tableName: 'todo_tasks' },
  { sheetName: 'Card Settlements', tableName: 'card_settlements' },
  { sheetName: 'Cash Reconciliation', tableName: 'cash_reconciliation' },
  { sheetName: 'Lost Opportunity', tableName: 'lost_opportunity' },
  { sheetName: 'Cash Advance Schedules', tableName: 'cash_advance_schedules' },
  { sheetName: 'Merchandise', tableName: 'merchandise' },
  { sheetName: 'Misc Sales', tableName: 'misc_sales' },
  { sheetName: 'Reviews', tableName: 'reviews' },
  { sheetName: 'Recurring Bills', tableName: 'recurring_bills' },
  { sheetName: 'Directory', tableName: 'directory' },
  { sheetName: 'Paw Card', tableName: 'paw_card_entries' },
  { sheetName: 'UI Errors', tableName: 'ui_errors' },
];

/** Tables with serial PK: use insert (omit id) or provide id from sheet if present. */
export const SERIAL_PK_TABLES = new Set([
  'card_settlements',
  'lost_opportunity',
  'reviews',
  'recurring_bills',
  'directory',
  'paw_card_entries',
]);

/** Per-sheet: sheet header → Supabase column. Only include entries that differ from identity (header !== db column). */
export const HEADER_TO_DB: Record<string, Record<string, string>> = {
  'Orders': { order_id: 'id', order_status: 'status' },
  'Order Items': { order_item_id: 'id' },
  'Order Add Ons': { order_addon_id: 'id' },
  'Payments': { payment_id: 'id' },
  'Fleet': { vehicle_id: 'id', GPS_ID: 'gps_id', Owner: 'owner' },
  'Expenses': {
    expense_id: 'id',
    Date: 'date',
    Category: 'category',
    Amount: 'amount',
    'Transfer Fee': 'transfer_fee',
    'Paid From': 'paid_from',
    Description: 'description',
  },
  'Card Settlements': {
    'Raw Date': 'raw_date',
    Name: 'name',
    'Ref Number': 'ref_number',
  },
  'Vehicle Swaps': { swap_id: 'id' },
  'Customers': { customer_id: 'id', customer_name: 'name' },
  'Journal Entries': { entry_id: 'id' },
  'Cash Reconciliation': { reconciliation_id: 'id', till_demons: 'till_denoms' },
  'Maintenance': {
    maintenance_id: 'id',
    timestamp: 'created_at',
    Status: 'status',
    Mechanic: 'mechanic',
    Odometer: 'odometer',
  },
  'Lost Opportunity': {
    Date: 'date',
    Time: 'time',
    'Vehicle Requested': 'vehicle_requested',
    'Duration (Days)': 'duration_days',
    'Est. Value': 'est_value',
    'Staff Notes': 'staff_notes',
  },
  'Employees': {
    'Employee ID': 'id',
    'Full Name': 'full_name',
    Role: 'role',
    '9PM Bonus Rate': 'nine_pm_bonus_rate',
    '13th Month Accrued': 'thirteenth_month_accrued',
    'SSS No.': 'sss_no',
    'PhilHealth No.': 'philhealth_no',
    'PagIBIG No.': 'pagibig_no',
    'Emergency Contact Name': 'emergency_contact_name',
    'Emergency Contact Number': 'emergency_contact_number',
    'Start Date': 'start_date',
    'Probation End Date': 'probation_end_date',
    'Rate Type': 'rate_type',
    'Basic Rate': 'basic_rate',
    'Overtime Rate': 'overtime_rate',
    'Commission Rate': 'commission_rate',
    'Monthly Bike Allowance': 'monthly_bike_allowance',
    'Bike Allowance Used': 'bike_allowance_used',
    'Bike Allowance Accrued': 'bike_allowance_accrued',
    'Available Balance': 'available_balance',
    'Current Cash Advance': 'current_cash_advance',
    'Holiday Allowance': 'holiday_allowance',
    'Holiday Used': 'holiday_used',
    'Sick Allowance': 'sick_allowance',
    'Sick Used': 'sick_used',
    'SSS Deduction Amt': 'sss_deduction_amt',
    'PhilHealth Deduction Amt': 'philhealth_deduction_amt',
    'PagIBIG Deduction Amt': 'pagibig_deduction_amt',
  },
  'Timesheets': {
    'Entry ID': 'id',
    'Employee ID': 'employee_id',
    'Time In': 'time_in',
    'Time Out': 'time_out',
    'Regular Hours': 'regular_hours',
    'Overtime Hours': 'overtime_hours',
    '9PM Returns (Count)': 'nine_pm_returns_count',
    'Daily Notes': 'daily_notes',
    'Payroll Status': 'payroll_status',
    'SIL Inflation': 'sil_inflation',
  },
  'Cash Advance Schedules': { schedule_id: 'id', amount: 'installment_amount' },
  'Transfers': { transfer_id: 'id', timestamp: 'created_at' },
  'To Do': { task_id: 'id', visability: 'visibility' },
  'Merchandise': {
    'Item SKU': 'sku',
    'Item Name': 'item_name',
    'Size/Variant': 'size_variant',
    'Cost Price': 'cost_price',
    'Sale Price': 'sale_price',
    'Starting Stock': 'starting_stock',
    'Sold Count': 'sold_count',
    'Current Stock': 'current_stock',
  },
  'Misc Sales': { 'sale-id': 'id', recieved_into: 'received_into' },
  'Reviews': { Store: 'store_id', 'Reviewer Name': 'reviewer_name', 'Replied?': 'replied' },
  'Recurring Bills': { store: 'store_id' },
  'Directory': { GCash: 'gcash_number' },
  'Paw Card': { timestamp: 'created_at' },
  'UI Errors': { error_id: 'id' },
};
